%   % Example 4: Advanced Subject Parsing (BIDS-like)
%   % Uses a regex to extract subject and session from BIDS-style filenames
%   % like 'sub-01_ses-pre_task-rest_eeg.set'.
  Out4 = study.extract_epoch( ...
      'study_path', 'C:\\EEG_Data\\BIDS_Study', ...
      'searchstring', '_eeg\.set$', ...
      'subject_parser', '(?<sub>sub-\d+)_<ses>ses-\w+)', ...
      'markers', {'response'});