


eeg_pipe = prep.Pipeline([], p) ...
    .addStep('Load', @prep.load_set, p.Input) ...
    .addStep('Remove Other chans', @prep.remove_channels, 'Chan2remove', p.ChanInfo.Chan2remove) ...
    .addStep('Downsample', @prep.downsample, p.Downsample) ...
    .addStep('Bandpass', @prep.filter, p.Filter) ...
    .addStep('Notch',@prep.remove_powerline, p.Powerline) ...
    .addStep('Crop by markers', @prep.crop_by_markers, p.Crop) ...
    .addStep('Bad channels', @prep.remove_bad_channels, p.BadChan) ...
    .addStep('Re-reference', @prep.reref, p.Reref) ...
    .addStep('ICA + prune', @prep.remove_bad_ICs, p.BadIC) ...
    .addStep('Intepolate', @prep.interpolate, 'LogFile',p.LogFile) ...
    .addStep('Save', @prep.save_set, p.Output) ...
    .run()
logPrint(p.LogFile,'--- All pipelines finished ---');