
EEGLAB_path = '/media/NAS/misc/matlab_toolbox/eeglab2023.1';
EEGdojo= '/media/NAS/misc/matlab_toolbox/EEGdojo';
FASTER_path =  '/media/NAS/misc/matlab_toolbox/FASTER';
addpath(genpath(EEGLAB_path))
addpath(genpath(FASTER_path))
addpath(genpath(EEGdojo))

clear; close all; clc;
%% Get subinfo
BIDS_path = sprintf( '/media/NAS/EEGdata/HBN_EEG_BIDS/cmi_bids_R%d', idx);

run('/media/NAS/EEGdata/HBN_EEG_BIDS/moviedm_code/prep_params_template_EGI.m')
derivative_path = fullfile(BIDS_path, 'derivatives/prep_mid');
if ~exist(derivative_path , 'dir')
    mkdir(derivative_path );
end
save(fullfile(derivative_path,'prep_parameters.mat'),'Params')
[subpath, subfile] = filesearch_regexp(BIDS_path, 'sub-.*MID_eeg\.set');


eeg_pipe = prep.Pipeline([], p) ...
    .addStep('Load', @prep.load_set, p.Input) ...
    .addStep('Remove Other chans', @prep.remove_channels, 'Chan2remove', p.ChanInfo.Chan2remove) ...
    .addStep('Downsample', @prep.downsample, p.Downsample) ...
    .addStep('Bandpass', @prep.filter, p.Filter) ...
    .addStep('Notch',@prep.remove_powerline, p.Powerline) ...
    .addStep('Crop by markers', @prep.crop_by_markers, p.Crop) ...
    .addStep('Bad channels', @prep.remove_bad_channels, p.BadChan) ...
    .addStep('Re-reference', @prep.reref, p.Reref) ...
    .addStep('ICA + prune', @prep.remove_bad_ICs, p.BadIC) ...
    .addStep('Intepolate', @prep.interpolate) ...
    .addStep('Epoch', @prep.segment_task, p.EpochTask) ...
    .addStep('Bad epochs', @prep.remove_bad_epochs) ...
    .addStep('Save', @prep.save_set, p.Output) ...
    .run();
logPrint(p.LogFile,'--- All pipelines finished ---');
